import multiprocessing 
import os
import time
import datetime
def hello_from_process_01():
    print(f'Привет от дочернего процесса 01 {os.getpid()}!')
    time.sleep(5)
def hello_from_process_02():
    for i in range(100000000):
        2+2
    print(f'Привет от дочернего процесса 02 {os.getpid()}!')
    time.sleep(5)
start = datetime.datetime.now()
if __name__ == '__main__':
    hello_process_01 = multiprocessing.Process(target=hello_from_process_01) 
    hello_process_01.start()
    hello_process_02 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_02.start()
    hello_process_03 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_03.start()
    hello_process_04 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_04.start()
    hello_process_05 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_05.start()
    hello_process_06 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_06.start()
    hello_process_07 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_07.start()
    hello_process_08 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_08.start()
    hello_process_09 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_09.start()
    hello_process_10 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_10.start()
    hello_process_11 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_11.start()
    hello_process_12 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_12.start()
    hello_process_13 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_13.start()
    hello_process_14 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_14.start()
    hello_process_15 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_15.start()
    hello_process_16 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_16.start()
    hello_process_17 = multiprocessing.Process(target=hello_from_process_02) 
    hello_process_17.start()
    print(f'Привет от родительского процесса {os.getpid()}')
    hello_process_01.join()
    hello_process_02.join()
    hello_process_03.join()
    hello_process_04.join()
    hello_process_05.join()
    hello_process_06.join()
    hello_process_07.join()
    hello_process_08.join()
    hello_process_08.join()
    hello_process_09.join()
    hello_process_10.join()
    hello_process_11.join()
    hello_process_12.join()
    hello_process_13.join()
    hello_process_14.join()
    hello_process_15.join()
    hello_process_16.join()
    hello_process_17.join()
finish = datetime.datetime.now()
print(finish - start)